### ISSUE TITLE
请问一下这个工具的具体功能是啥？

### ISSUE THREAD

**Issue by xiaohuazi123** [ap0405140/MSSQLLogAnalyzer#1]
看到是微软mssql方向MVP，幸会幸会，请问这个工具具体功能是啥，项目介绍写的优点简单喔

**Comment by ap0405140** [comment]
你好, 请参考博文: https://blog.csdn.net/ap0405140/article/details/50518190

**Comment by xiaohuazi123** [comment]
好的
