### ISSUE TITLE
无法查询到最近一次checkpoint前的数据

### ISSUE THREAD

**Issue by qincast** [ap0405140/MSSQLLogAnalyzer#5]
fn_dblog这个函数能查到的log好像会在checkpoint 之后回收，请问有没有什么好的解决办法呢

**Comment by ap0405140** [comment]
你好,满足以下2个条件时,fn_dblog查询到的日志不会因checkpoint而中断,
1.数据库的恢复模式为[完整].
2.数据库至少做过一次完整备份.

之后如有做数据库日志备份,则需用fn_dump_dblog读取对应的日志备份文件,其返回格式与fn_dblog相似.

**Comment by qincast** [comment]
感谢~~！
